# Generated by Django 4.0.4 on 2022-05-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_orderproduct'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
