# Generated by Django 4.0.4 on 2022-05-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_brand_table_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='shop_brands',
        ),
        migrations.AlterModelTable(
            name='category',
            table='shop_categories',
        ),
        migrations.AlterModelTable(
            name='product',
            table='shop_products',
        ),
    ]
